<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFrameworks>net8.0;.netstandard2.1</TargetFrameworks>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.30.2" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="9.0.3" />
  </ItemGroup>

</Project>
